### ISSUE TITLE
Parser completely removes body elements if html string has open <html> and <body> tags, but does not have close </body> and tag

### ISSUE THREAD

**Issue by sanex3339** [remarkablemark/html-dom-parser#18]
## Expected Behavior

Parser should try to keep all existing html tags if html string has open <html> and <body> tags, but does not have close </body> and </html> tags

## Actual Behavior

Parser completely removes all `html` children elements if html string has open <html> and <body> tags, but does not have close </body> tag

## Steps to Reproduce

Just try to parse following html string:
```
 <html>
        <body>
          <h1 style="font-family: Arial;">
            html-react-parser
          </h1>
```

## Reproducible Demo

https://jsfiddle.net/d2g59ch4/

## Environment

- Version: 0.2.2
- Platform: Mac OS
- Browser: Chrome 77

**Comment by sanex3339** [comment]
So, looks like the problem is here:
https://github.com/remarkablemark/html-dom-parser/blob/master/lib/domparser.js#L140

**Comment by remarkablemark** [comment]
Thanks for opening this issue (and closing remarkablemark/html-react-parser#126) @sanex3339

I can confirm that this is a bug. Along with your fiddle, I can reproduce that this happens on the client parser (see [repl](https://repl.it/@remarkablemark/html-dom-parser-18-2)) and not on the server parser (see [repl](https://repl.it/@remarkablemark/html-dom-parser-18-1)).

Would you be interested in making a fix? Otherwise, I should have some time over the weekend to work on it.

**Comment by sanex3339** [comment]
Hi, unfortunately, I haven't time to fix this bug, but I can wait until you'll fix it.

**Comment by remarkablemark** [comment]
No worries, I'll update you know once I have the fix.

**Comment by remarkablemark** [comment]
[`html-dom-parser@0.2.3`](https://github.com/remarkablemark/html-dom-parser/releases/tag/v0.2.3) has been released and published:

```sh
# update with npm
npm i -S html-dom-parser@0.2.3

# or with yarn
yarn add html-dom-parser@0.2.3
```

I'll have a followup PR for [html-react-parser](https://github.com/remarkablemark/html-react-parser).

**Comment by sanex3339** [comment]
Thank you!
