### ISSUE TITLE
fails to parse complex html with script tags

### ISSUE THREAD

**Issue by rburgst** [remarkablemark/html-dom-parser#25]
## Expected Behavior

all tags should be parsed

## Actual Behavior

the last 2 tags `p` and `audio` are omitted and instead show up in the above `div`.

## Steps to Reproduce

see PR that adds a failing test case

https://github.com/remarkablemark/html-dom-parser/pull/24

## Reproducible Demo

see PR https://github.com/remarkablemark/html-dom-parser/pull/24
## Environment

- Version: 0.2.3
- Platform: Mac OSX (mocha)
- Browser: N/A

**Comment by rburgst** [comment]
I guess the reason is that we cannot pass `{xmlMode: true}` to `htmlparser2', see https://github.com/remarkablemark/html-react-parser/issues/158

**Comment by remarkablemark** [comment]
Similar to my comment in the remarkablemark/html-react-parser#158, the reason the nesting is off is because self-closing syntax (`/>`) is used on non-void HTML elements:

```html
<div class="wp-playlist-next"/>
<div class="wp-playlist-prev"/>
```

I opened PR #26 which validates that `<audio>` and other elements can be parsed.

The reason tests are failing in #24 is because jsdom is decoding HTML entities by default (so I updated the test parsers to alway have `decodeEntities` enabled) and `<noscript>` is not rendering the children as nodes but as text in jsdom.

**Comment by remarkablemark** [comment]
Given #24 and remarkablemark/html-react-parser#158 have been resolved, can we close this issue?

**Comment by rburgst** [comment]
of course. Note that I finally got to the bottom of the issue. The real culprit was https://github.com/cheeriojs/cheerio/issues/1235

**Comment by remarkablemark** [comment]
Hmm... I don't think it's `cheerio` because that package also depends on `htmlparser2` (see [here](https://github.com/cheeriojs/cheerio/blob/1.0.0-rc.3/package.json#L31))

**Comment by rburgst** [comment]
it surely is, I get a valid html before then cherio auto closes the empty `<div></div>` tags to `<div/>` by adding the workaround (empty text node) via 
```
$('div').filter((i,e) => !e.children.length).text(''))
```
I was able to work around the problem

**Comment by remarkablemark** [comment]
I see what you mean. You're using `cheerio` in your project and then parsing the output with this library

**Comment by rburgst** [comment]
Correct.
