### ISSUE TITLE
Convert back DOM elements to string

### ISSUE THREAD

**Issue by tyzion** [remarkablemark/html-dom-parser#369]
Hi,

Is it possible to convert back the parsed string?

Because I'd like to delete the last empty tags from a string, and I really don't know how to do it if not by parsing the text into dom elements, remove empty tags, and then convert it all back.

Thanks :)

**Comment by remarkablemark** [comment]
@tyzion unfortunately this library does not have the ability to convert DOM nodes back to HTML string.

Since this library uses/mimics `htmlparser2`, I checked if the library has a native solution:

- https://github.com/fb55/htmlparser2/issues/22
- https://github.com/fb55/htmlparser2/issues/5

It doesn't look like it.

However, I found [htmlparser-to-html](https://www.npmjs.com/package/htmlparser-to-html). It might do what you need although I haven't tried it.

**Comment by tyzion** [comment]
@remarkablemark Thank you soooo much for your answer and your time!

I couldn't find anything! Thanks a lot, man

**Comment by remarkablemark** [comment]
No problem, I'll be closing this issue then!
